---
- name: default
  hosts: all
  roles:
    - takel-takelage
  tasks:
    - name: (converge) install deb prerequisites
      package:
        name: "{{ item }}"
      loop:
        - procps
        - python3-yaml
