---
takel_gem_gems:
  - name: aruba
    version: 1.0.0
    description: cli test framework
  - name: rubocop
    version: 0.81.0
    description: ruby linter
  - name: rspec
    version: 3.9.0
    description: test framework
  - name: takelage
    version: 0.12.2
    description: takelage cli
  - name: yard
    version: 0.9.24
    description: documentation
