---
- name: (autoupgrade) install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: (autoupgrade) copy 20auto-upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  notify: restart unattended-upgrades

- name: (autoupgrade) copy 50unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  notify: restart unattended-upgrades
