---
- name: (install) install deb packages
  package:
    name: "{{ takel_terra_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) download terraform binary
  unarchive:
    src: "{{ takel_terra_terraform_url }}"
    dest: "{{ takel_terra_bin_path }}"
    remote_src: true
    mode: 0755

- name: (install) download terragrunt binary
  get_url:
    url: "{{ takel_terra_terragrunt_url }}"
    dest: "{{ takel_terra_bin_path }}/{{ takel_terra_terragrunt_binary }}"
    mode: 0755
