---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_terra
    - takel_terra_install

- name: (main) include configure
  import_tasks: configure.yml
  tags:
    - takel
    - takel_terra
    - takel_terra_configure
