---
- name: (install) install packages
  package:
    name: "{{ takel_rvm_deb_install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: (install) detect rvm installer
  stat:
    path: "{{ takel_rvm_rvm_installer }}"
  register: takel_rvm_path_rvm_installer

- name: (install) detect current rvm version
  command: "{{ takel_rvm_rvm_binary }} version"
  register: takel_rvm_rvm_current_version
  when: takel_rvm_path_rvm_binary.stat.exists

- name: (install) download rvm installer
  get_url:
    url: "{{ takel_rvm_url_rvm_installer }}"
    dest: "{{ takel_rvm_rvm_installer }}"
    mode: 0755
  when: not takel_rvm_path_rvm_installer.stat.exists

- name: (install) import gpg keys from keyservers
  shell: >-
    gpg --batch
    --keyserver {{ takel_rvm_gpg_keyserver }}
    --recv-keys {{ takel_rvm_gpg_key_ids }}
  register: takel_rvm_gpg_keys_import
  ignore_errors: True

- name: (install) copy gpg keys file to host
  copy:
    content: "{{ takel_rvm_gpg_keys }}"
    dest: "{{ takel_rvm_gpg_temp_keys_file }}"
  when: takel_rvm_gpg_keys_import.rc != 0

- name: (install) import gpg keys from file
  command: "gpg --batch --import {{ takel_rvm_gpg_temp_keys_file }}"
  when: takel_rvm_gpg_keys_import.rc != 0

- name: (install) remove gpg keys file from host
  file:
    path: "{{ takel_rvm_gpg_temp_keys_file }}"
    state: absent
  when: takel_rvm_gpg_keys_import.rc != 0

- name: (install) install rvm
  shell: >-
    {{ takel_rvm_rvm_installer }}
    {{ takel_rvm_rvm_version }}
    --path {{ takel_rvm_install_path }}
    {{ takel_rvm_install_flags }}
