---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_install

- name: (main) include sudo
  import_tasks: sudo.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_sudo

- name: (main) include pyscripts
  import_tasks: pyscripts.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_pyscripts

- name: (main) include gnupg
  import_tasks: gnupg.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_gnupg

- name: (main) include profile
  import_tasks: profile.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_profile
