---
- name: (configure) create completion dir
  file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: (configure) copy completion file
  copy:
    src: molecule
    dest: "{{ takel_molecule_completion_path }}"
    owner: root
    group: root
    mode: 0644
