---
takel_docker_deb_preinstall_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - gnupg-agent
  - software-properties-common

takel_docker_deb_install_packages:
  - containerd.io
  - docker-ce
  - docker-ce-cli

takel_docker_ce_repo_key: https://download.docker.com/linux/debian/gpg
takel_docker_ce_repo_string: deb https://download.docker.com/linux/debian buster stable
takel_docker_ce_completion_path: /etc/bash_completion.d/docker
takel_docker_ce_completion_url: https://github.com/docker/cli/raw/master/contrib/completion/bash/docker
