---
takel_takelage_deb_install_packages:
  - git
  - gnupg
  - expect
  - mmv
  - socat
  - sudo
  - tree
  - vim
  - vim-scripts

takel_takelage_gpg_config_files:
  - gpg-agent.conf
  - gpg.conf
  - dirmngr.conf

takel_takelage_entrypoint_path: /

takel_takelage_profile:
  - file: aliases.sh
    order: 50
  - file: make.sh
    order: 50
  - file: prompt.sh
    order: 50
  - file: tau.sh
    order: 50
