---
takel_gopass_deb_preinstall_packages:
  - apt-transport-https
  - ca-certificates

takel_gopass_deb_install_packages:
  - gopass

takel_gopass_version: 1.8.6
takel_gopass_deb: gopass-{{ takel_gopass_version }}-linux-amd64.deb
takel_gopass_tmp: "/tmp/{{ takel_gopass_deb }}"
takel_gopass_url: "https://github.com/gopasspw/gopass/releases/download/v{{ takel_gopass_version }}/{{ takel_gopass_deb }}"

takel_gopass_autocompletion: source <(gopass completion bash)