---
driver:
  name: docker
platforms:
  - name: "molecule-takelage-dev-packer"
    image: "packer_local/takelage-dev:prod"
    override_command: true
    command: /debug/entrypoint.py --debug --username testuser --uid 1010 --gid 1010 --host /testhome/testuser --no-gopass --no-ssh --no-gpg --no-git --no-docker
    tty: true
    volumes:
      - ${TAKELAGE_PROJECT_BASE_DIR}/ansible/roles/takelage-dev/files/pyscripts:/debug
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    # m: debug
    s: true
    testvars-no-gather-facts: true
    v: true
  env:
    # exclude external role which takeltest can't handle
    TESTVARS_ROLES_BLACKLIST: github-rvm_rvm1-ansible
scenario:
  name: image_prod
  create_sequence:
    - create
  converge_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - check
    - destroy
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - verify
    - destroy
