---
driver:
  name: docker
platforms:
  - name: "molecule-takelage-dev-packer"
    image: "packer_local/takelage-dev:prod"
    override_command: true
    command: /entrypoint.py --username testuser --uid 1010 --gid 1010 --home /testhome/testuser --no-bit --no-docker --no-git --no-gopass --no-gpg --no-ssh
    tty: true
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    # m: debug
    s: true
    testvars-no-gather-facts: true
    v: true
  env:
    # exclude external role which takeltest can't handle
    TESTVARS_ROLES_BLACKLIST: github-rvm_rvm1-ansible
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - check
    - destroy
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - verify
    - destroy
