---
- name: (main) include preinstall
  import_tasks: preinstall.yml
  tags:
    - takel
    - takel_gopas
    - takel_gopass_preinstall

- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_install

- name: (main) include configure
  import_tasks: configure.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_configure
