---
- name: (playbook-project-prod) create project prod
  hosts: all
  roles:
    - takel-base
    - takel-anarchism
    - takel-takelage-dev
    - takel-docker
    - takel-bit-client
    - takel-cleanup
