---
- name: (configure) create completion dir
  file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: 0755

# https://gohugo.io/commands/hugo_gen_autocomplete/
- name: (configure) add hugo autocompletion
  command: hugo gen autocomplete
  args:
    creates: /etc/bash_completion.d/hugo.sh
