name: Build, test and deploy project

on:
  push: # trigger on git push
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-test-and-deploy-project:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takelage

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage-dev
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Test takelscripts
        run: tau docker container command "rake takelscripts"

      - name: Build takelage project image with packer
        run: tau docker container command "rake image:docker:takelbase:project:prod:from_base"

      - name: Test takelage project image
        run: tau docker container command "rake image:docker:takelbase:project:prod:test"

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        run: |
          tau docker container command "rake dockerhub:takelbase:project:prod:registry:tag"
          tau docker container command "rake dockerhub:takelbase:project:prod:registry:push -l debug"
