---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_packer
    - takel_packer_install

- name: (main) include configure
  import_tasks: configure.yml
  tags:
    - takel
    - takel_packer
    - takel_packer_configure
